---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
  labels:
    app: logging
spec:
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - name: logging
        image: imgvar       
        ports:
        - containerPort: 5000
        resources:
          requests: 
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "2000Mi"
            cpu: "1000m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              key: aspnetenvlogging
              name: chaves-logging